<?php

namespace TaxiBundle\Repository;

/**
 * CategorieTaxiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieTaxiRepository extends \Doctrine\ORM\EntityRepository
{
    function SearchVelo($libelle){
        $query=$this->getEntityManager()->createQuery("select e from TaxiBundle:CategorieTaxi e where e.model LIKE '%$libelle%'");
        return $query->getResult();

    }
}
