<?php

namespace ReclamationBundle\Repository;

/**
 * typeReclamationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class typeReclamationRepository extends \Doctrine\ORM\EntityRepository
{
}
