offre_index:
    path:     /
    defaults: { _controller: "OffreBundle:Offre:list" }
    methods:  GET

offre_list:
    path:     /list
    defaults: { _controller: "OffreBundle:Offre:list" }
    methods:  GET
search:
    path:     /search
    defaults: { _controller: "OffreBundle:Offre:search" }
    methods:  GET
offre_show:
    path:     /{idOffre}/show
    defaults: { _controller: "OffreBundle:Offre:show" }
    methods:  GET

offre_new:
    path:     /new
    defaults: { _controller: "OffreBundle:Offre:new" }
    methods:  [GET, POST]

offre_edit:
    path:     /{idOffre}/edit
    defaults: { _controller: "OffreBundle:Offre:edit" }
    methods:  [GET, POST]

offre_delete:
    path:     /{idOffre}/delete
    defaults: { _controller: "OffreBundle:Offre:delete" }
    methods:  DELETE
