<?php

namespace VeloBundle\Repository;

/**
 * veloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VeloRepository extends \Doctrine\ORM\EntityRepository
{
    function SearchVelo($libelle){
        $query=$this->getEntityManager()->createQuery("select e from VeloBundle:Velo e where e.type LIKE '%$libelle%'");
        return $query->getResult();

    }
function prix($id){
    $query=$this->getEntityManager()->createQuery("select e.prix from VeloBundle:Velo e where e.id = '$id'");
    return $query->getResult();
}
}
