avis_index:
    path:     /
    defaults: { _controller: "AvisBundle:Avis:index" }
    methods:  GET

avis_show:
    path:     /{idAvis}/show
    defaults: { _controller: "AvisBundle:Avis:show" }
    methods:  GET

avis_new:
    path:     /new
    defaults: { _controller: "AvisBundle:Avis:new" }
    methods:  [GET, POST]

avis_edit:
    path:     /{idAvis}/edit
    defaults: { _controller: "AvisBundle:Avis:edit" }
    methods:  [GET, POST]

avis_delete:
    path:     /{idAvis}/delete
    defaults: { _controller: "AvisBundle:Avis:delete" }
    methods:  DELETE
