taxi_homepage:
    path:     /
    defaults: { _controller: TaxiBundle:Default:index }
service_GetTaxi:
    path:    /serviceGetTaxi/{id_chauffeur}
    defaults: { _controller: TaxiBundle:Default:serviceGetTaxi }