taxi_taxi:
    resource: "@TaxiBundle/Resources/config/routing/taxi.yml"
    prefix:   /taxi

taxi_categorietaxi:
    resource: "@TaxiBundle/Resources/config/routing/categorietaxi.yml"
    prefix:   /categorietaxi

taxi_homepage:
    path:     /
    defaults: { _controller: TaxiBundle:Default:index }

add:
    path:     /add
    defaults: { _controller: TaxiBundle:Categorie:add }
