chauffeur_serviceSetChauffeur:
    path:     /serviceSetChauffeur/{adresse}/{cin}/{permis}/{nom}/{prenom}/{photo}/{id}
    defaults: { _controller: ChauffeurBundle:Default:ServiceSetChauffeur }

chauffeur_homepage:
    path:     /
    defaults: { _controller: ChauffeurBundle:Default:index }

userProfile_page_chauffeur:
    path:     /userProfile
    defaults: { _controller: ChauffeurBundle:Default:userProfile }

chauffeur_index:
    path:     /Show
    defaults: { _controller: ChauffeurBundle:Default:Show }