evenement_inscription:
    resource: "@EvenementBundle/Resources/config/routing/inscription.yml"
    prefix:   /inscription

evenement_homepage:
    resource: "@EvenementBundle/Resources/config/routing/event.yml"
    prefix:   /
