reclamation_index:
    path:     /
    defaults: { _controller: "ReclamationBundle:Reclamation:index" }
    methods:  GET

reclamation_show:
    path:     /{idRec}/show
    defaults: { _controller: "ReclamationBundle:Reclamation:show" }
    methods:  GET

reclamation_new:
    path:     /new/{idChauffeur}
    defaults: { _controller: "ReclamationBundle:Reclamation:new" }
    methods:  [GET, POST]

reclamation_edit:
    path:     /{idRec}/edit
    defaults: { _controller: "ReclamationBundle:Reclamation:edit" }
    methods:  [GET, POST]

reclamation_delete:
    path:     /{idRec}/delete
    defaults: { _controller: "ReclamationBundle:Reclamation:delete" }
    methods:  DELETE

reclamation_newM:
    path:     /newM/{idClient}/{idchauffeur}/{typeReclamation}
    defaults: { _controller: "ReclamationBundle:Reclamation:newM" }
    methods:  [GET, POST]

reclamation_showM:
    path:     /showReclamation/{id}
    defaults: { _controller: "ReclamationBundle:Reclamation:showReclamation" }
    methods:  [GET, POST]
reclamation_getTypesM:
    path:     /getTypes
    defaults: { _controller: "ReclamationBundle:Reclamation:getTypes" }
    methods:  [GET, POST]