<?php

namespace OffreBundle\Repository;

/**
 * offreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OffreRepository extends \Doctrine\ORM\EntityRepository
{

    function SearchOffre($libelle){
    $query=$this->getEntityManager()->createQuery("select e from OffreBundle:Offre e where e.type LIKE '%$libelle%'");
    return $query->getResult();

}

}
