<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Notification;
use AppBundle\Entity\user;

/**
 * NotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationRepository extends \Doctrine\ORM\EntityRepository
{
    public function AllMark($id){
        $em=$this->getEntityManager();
        $queryBuilder = $em->createQueryBuilder();
        $queryBuilder
            ->update(Notification::class, 'u')
            ->set('u.seen', 1)
            ->where('u.idReceive = ?1')
            ->setParameter(1, $id)
            ->getQuery()
            ->execute();
    }
}
