<?php

namespace AppBundle\Repository;

/**
 * userRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class userRepository extends \Doctrine\ORM\EntityRepository
{
    public function last(){
        $query=$this->getEntityManager()->createQuery(
            '
            SELECT
            u
            FROM
            AppBundle\Entity\User u
            ORDER BY u.id DESC
            '
        )->setMaxResults(1);

        return $query->getResult();
    }
}
