avis:
    resource: "@AvisBundle/Resources/config/routing.yml"
    prefix:   /Avis

offre:
    resource: "@OffreBundle/Resources/config/routing.yml"
    prefix:   /Offre

evenement:
    resource: "@EvenementBundle/Resources/config/routing.yml"
    prefix:   /Evenement

velo:
    resource: "@VeloBundle/Resources/config/routing.yml"
    prefix:   /Velo

taxi:
    resource: "@TaxiBundle/Resources/config/routing.yml"
    prefix:   /Taxi

reclamation:
    resource: "@ReclamationBundle/Resources/config/routing.yml"
    prefix:   /reclamation

reservation:
    resource: "@ReservationBundle/Resources/config/routing.yml"
    prefix:   /Reservation

chauffeur:
    resource: "@ChauffeurBundle/Resources/config/routing.yml"
    prefix:   /chauffeur

client:
    resource: "@CLientBundle/Resources/config/routing.yml"
    prefix:   /client

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
app:
    resource: '@AppBundle/Controller/'
    type: annotation
