velo_location:
    resource: "@VeloBundle/Resources/config/routing/location.yml"
    prefix:   /location

velo_homepage:
    resource: "@VeloBundle/Resources/config/routing/velo.yml"
    prefix:   /

