reservation_index:
    path:     /
    defaults: { _controller: "ReservationBundle:Reservation:index" }
    methods:  GET

_show:
    path:     /{idReservation}/show
    defaults: { _controller: "ReservationBundle:Reservation:show" }
    methods:  GET

reservation_homepage:
    path:     /new
    defaults: { _controller: "ReservationBundle:Reservation:new" }
    methods:  [GET, POST]

_edit:
    path:     /{idReservation}/edit
    defaults: { _controller: "ReservationBundle:Reservation:edit" }
    methods:  [GET, POST]

_delete:
    path:     /{idReservation}/delete
    defaults: { _controller: "ReservationBundle:Reservation:delete" }
    methods:  DELETE

service_AddReservation:
    path: /serviceAddReservation/{idChauffeur}/{idClient}/{depart}/{arrive}/{prix}/{typeReservation}/{latitude}/{longitude}/{latitude2}/{longitude2}
    defaults: { _controller: "ReservationBundle:Reservation:serviceAddReservation" }

service_GetReservation:
    path: /serviceGetReservation/{idReservation}
    defaults: { _controller: "ReservationBundle:Reservation:serviceGetReservation" }

service_CheckReservation:
    path: /serviceCheckReservation/{idChauffeur}
    defaults: { _controller: "ReservationBundle:Reservation:serviceCheckReservation" }