event_index:
    path:     /
    defaults: { _controller: "EvenementBundle:Event:index" }
    methods:  GET

event_show:
    path:     /{idEvent}/show
    defaults: { _controller: "EvenementBundle:Event:show" }
    methods:  GET

event_new:
    path:     /new
    defaults: { _controller: "EvenementBundle:Event:new" }
    methods:  [GET, POST]

event_edit:
    path:     /{idEvent}/edit
    defaults: { _controller: "EvenementBundle:Event:edit" }
    methods:  [GET, POST]

event_delete:
    path:     /{idEvent}/delete
    defaults: { _controller: "EvenementBundle:Event:delete" }
    methods:  DELETE
