<?php

namespace EvenementBundle\Repository;

/**
 * inscriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InscriptionRepository extends \Doctrine\ORM\EntityRepository
{    function SearchiOffre($libelle){
    $query=$this->getEntityManager()->createQuery("select i.id, e.idEvent, e.nom, u.id, u.username FROM EvenementBundle\Entity\Inscription i, EvenementBundle\Entity\Event e , AppBundle\Entity\User u
                                                        WHERE i.idEvent=e.idEvent and i.idClient=u.id and e.nom LIKE '%$libelle%'"


    );

    return $query->getResult();

}
}
