<?php

namespace EvenementBundle\Repository;

/**
 * inscriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InscriptionRepository extends \Doctrine\ORM\EntityRepository
{    function SearchiOffre($libelle){
    $query=$this->getEntityManager()->createQuery("select e from EvenementBundle:Inscription e where e.id LIKE '%$libelle%'");

    return $query->getResult();

}
}
