<?php

namespace AvisBundle\Repository;

/**
 * avisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AvisRepository extends \Doctrine\ORM\EntityRepository
{
    public function ListeAvis($idChauffeur){
        $query=$this->getEntityManager()->createQuery(
            '
            SELECT
            a.idAvis,a.msg,a.note,u.username
            FROM
            AvisBundle\Entity\Avis a,AppBundle\Entity\User u
            WHERE
            a.idCclient=u.idUser and a.idChauffeur=idChauffeur
            '
        )->setParameter('idChauffeur',$idChauffeur);

        return $query->getResult();
    }
}
